// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Para migraciones/CLI: usa la conexión directa (sin pgbouncer) cuando
    // esté disponible (Supabase en producción); en local, DIRECT_URL no
    // existe y cae de vuelta a DATABASE_URL (ya es una conexión directa).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
